---
- name: Install Apache
  yum: 
    name: httpd 
    state: present
  tags:
    - install_apache

- name: Disable SELinux
  selinux:
    state: disabled
  tags:
    - install_apache

- name: Set SELinux in permissive mode
  command: setenforce 0
  ignore_errors: true
  changed_when: false
  tags:
    - install_apache