---
- name: Install PHP REMI 7.4 
  yum:
    name: '{{ remi_repo_url }}'
    state: present
  tags:
    - install_php

- name: Install PHP modules
  yum: 
    name: '{{ item }}' 
    state: present
    enablerepo: "remi-php74"
  with_items: '{{ php_packages }}'
  notify: 
    - restart apache
  tags:
    - install_php