---
- include: install-apache.yml
  when: "'web_servers' in group_names and ansible_distribution == 'CentOS'"
  tags:
    - install_apache

- include: install-php.yml
  when: "'web_servers' in group_names and ansible_distribution == 'CentOS'"
  tags:
    - install_php

- include: install-wp.yml
  when: "'wp_servers' in group_names and ansible_distribution == 'CentOS'"
  tags:
    - install_wp